Bgee Adapter: gene expressed in anatomical entity
rejuve-bio/biocypher-kg pull request #12
Opened 2024-07-19 11:42 UTC by dawit-melka

- implement Bgee adapter
- user can choose writer class from command line

2024-07-22 17:09 UTC, Habush commented on config/schema_config.yaml
> +  id_prefixes:
What the purpose `id_prefixes`? Is it used in the writer class to deterimine the type of a node?

2024-07-22 17:17 UTC, Habush requested changes

2024-07-22 17:17 UTC, Habush commented on biocypher_metta/adapters/bgee_adapter.py
> +                score = data[BgeeAdapter.INDEX['expression_score']]
In addition to `anatomical_entity` and `expression_score` fields, add `FDR` field as `pvalue`.

2024-07-22 17:17 UTC, Habush commented on biocypher_metta/adapters/bgee_adapter.py
> +                data = line.split('\t')
For now, we're only interested in relationships whose `Expression` column value is `present`. So filter out rows with `absent` field value in the `Expression` column.

2024-07-24 14:12 UTC, Habush requested changes

2024-07-25 06:30 UTC, dawit-melka commented on biocypher_metta/adapters/bgee_adapter.py
> +                anatomical_entities = data[BgeeAdapter.INDEX['anatomical_entity']].split(' ∩ ')
There are some rows in the dataset with anatomical entity represented by`UBERON` and `CL` id separated by  this `∩` symbol (I think it is a symbol for `and` / `intersection`. I have included this row in the example sample dataset at top of the adapter.

2024-07-25 09:49 UTC, Habush approved these changes

2024-07-25 09:49 UTC, Habush commented on config/schema_config.yaml
> +      holds between a gene and an anatomical entity in which it is expressed
Can you change `anatomical entity` to `ontology term`

2024-07-25 13:07 UTC, merged