Express_in
rejuve-bio/biocypher-kg pull request #23
Opened 2024-08-23 09:06 UTC by Basliel-Amsalu

an adapter for extracting express in relationship between gene and ontology from gtex dataset

2024-08-29 10:08 UTC, dawit-melka requested changes

2024-08-29 10:08 UTC, dawit-melka commented on biocypher_metta/adapters/gtex_expression_adapter.py
> +                        _props = {}
could you add `p_value` as a property?

2024-08-29 10:08 UTC, dawit-melka commented on config/adapters_config_sample.yaml
It looks there a lot changes in this and other config files please review them and only commit necessary changes

2024-08-30 04:17 UTC, Basliel-Amsalu commented on config/schema_config.yaml
> +gtex gene to ontology expression:
but the other one is for variant to gene association this is for gene and ontologie

2024-08-30 08:11 UTC, dawit-melka commented on config/schema_config.yaml
> +gtex gene to ontology expression:
have you checked this one? - [expressed in:](https://github.com/rejuve-bio/biocypher-kg/blob/31467c3598f6fa671dd41fa09a2e1bc7a36d2d20/config/schema_config.yaml#L464)

2024-08-30 09:10 UTC, merged